// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Credenciais publicáveis do Supabase — devem ser injetadas como variáveis
// de ambiente no build (VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY).
// O fallback hardcoded foi REMOVIDO: um build sem env vars apontava silenciosamente
// para produção, corrompendo dados em ambientes de staging/CI. Agora falha rápido.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string;
const SUPABASE_PUBLISHABLE_KEY = (
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY ||
  import.meta.env.VITE_SUPABASE_ANON_KEY
) as string;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "[supabase/client] VITE_SUPABASE_URL e VITE_SUPABASE_ANON_KEY são obrigatórios. " +
    "Verifique o arquivo .env ou as variáveis de ambiente do deploy."
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});